package id.thoriq.dev.footballmatch.entity

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Match(
    @SerializedName("idEvent") val idEvent: Int,
    @SerializedName("idSoccerXML") val idSoccerXML: Int,
    @SerializedName("strEvent") val strEvent: String,
    @SerializedName("strFilename") val strFilename: String,
    @SerializedName("strSport") val strSport: String,
    @SerializedName("idLeague") val idLeague: Int,
    @SerializedName("strLeague") val strLeague: String,
    @SerializedName("strSeason") val strSeason: Int,
    @SerializedName("strDescriptionEN") val strDescriptionEN: String,
    @SerializedName("strHomeTeam") val strHomeTeam: String,
    @SerializedName("strAwayTeam") val strAwayTeam: String,
    @SerializedName("intHomeScore") val intHomeScore: Int,
    @SerializedName("intRound") val intRound: Int,
    @SerializedName("intAwayScore") val intAwayScore: Int,
    @SerializedName("intSpectators") val intSpectators: String,
    @SerializedName("strHomeGoalDetails") val strHomeGoalDetails: String,
    @SerializedName("strHomeRedCards") val strHomeRedCards: String?,
    @SerializedName("strHomeYellowCards") val strHomeYellowCards: String?,
    @SerializedName("strHomeLineupGoalkeeper") val strHomeLineupGoalkeeper: String,
    @SerializedName("strHomeLineupDefense") val strHomeLineupDefense: String,
    @SerializedName("strHomeLineupMidfield") val strHomeLineupMidfield: String,
    @SerializedName("strHomeLineupForward") val strHomeLineupForward: String,
    @SerializedName("strHomeLineupSubstitutes") val strHomeLineupSubstitutes: String,
    @SerializedName("strHomeFormation") val strHomeFormation: String,
    @SerializedName("strAwayRedCards") val strAwayRedCards: String?,
    @SerializedName("strAwayYellowCards") val strAwayYellowCards: String?,
    @SerializedName("strAwayGoalDetails") val strAwayGoalDetails: String,
    @SerializedName("strAwayLineupGoalkeeper") val strAwayLineupGoalkeeper: String,
    @SerializedName("strAwayLineupDefense") val strAwayLineupDefense: String,
    @SerializedName("strAwayLineupMidfield") val strAwayLineupMidfield: String,
    @SerializedName("strAwayLineupForward") val strAwayLineupForward: String,
    @SerializedName("strAwayLineupSubstitutes") val strAwayLineupSubstitutes: String,
    @SerializedName("strAwayFormation") val strAwayFormation: String,
    @SerializedName("intHomeShots") val intHomeShots: Int,
    @SerializedName("intAwayShots") val intAwayShots: Int,
    @SerializedName("dateEvent") val dateEvent: String,
    @SerializedName("datetimeEventUTC") val datetimeEventUTC: String,
    @SerializedName("strDate") val strDate: String,
    @SerializedName("strTime") val strTime: String,
    @SerializedName("strTVStation") val strTVStation: String,
    @SerializedName("idHomeTeam") val idHomeTeam: Int,
    @SerializedName("idAwayTeam") val idAwayTeam: Int,
    @SerializedName("strResult") val strResult: String,
    @SerializedName("strCircuit") val strCircuit: String,
    @SerializedName("strCountry") val strCountry: String,
    @SerializedName("strCity") val strCity: String,
    @SerializedName("strPoster") val strPoster: String,
    @SerializedName("strFanart") val strFanart: String,
    @SerializedName("strThumb") val strThumb: String,
    @SerializedName("strBanner") val strBanner: String,
    @SerializedName("strMap") val strMap: String,
    @SerializedName("strTweet1") val strTweet1: String,
    @SerializedName("strTweet2") val strTweet2: String,
    @SerializedName("strTweet3") val strTweet3: String,
    @SerializedName("strVideo") val strVideo: String,
    @SerializedName("strLocked") val strLocked: String
) : Parcelable